# GA3 BA  

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score


## Process the train data  

In [30]:
train = pd.read_csv('train_LR.csv')
train.head()

Tier  FICO  Term   Amount  Previous_Rate  Competition_rate  Rate  \
0     2   729    66  22000.0            -10              5.75  6.29   
1     1   786    60  37000.0            -10              4.09  4.09   
2     1   742    60  25000.0            -10              3.99  3.99   
3     1   631    60  25000.0            -10              4.59  4.49   
4     4   656    72  27300.0            -10              5.35  7.99   

   Cost_Funds  Partner Bin  Car_Type_N  Car_Type_R  Car_Type_U  Accept  
0      1.1625            1           0           0           1       1  
1      1.1400            2           1           0           0       0  
2      1.1163            3           1           0           0       0  
3      1.6150            1           1           0           0       0  
4      1.1200            1           0           0           1       1

In [31]:
train.shape

(109244, 13)

In [32]:
train.columns

Index(['Tier', 'FICO', 'Term', 'Amount', 'Previous_Rate', 'Competition_rate',
       'Rate', 'Cost_Funds', 'Partner Bin', 'Car_Type_N', 'Car_Type_R',
       'Car_Type_U', 'Accept'],
      dtype='object')

In [33]:
train.isna().sum()

Tier                0
FICO                0
Term                0
Amount              0
Previous_Rate       0
Competition_rate    0
Rate                0
Cost_Funds          0
Partner Bin         0
Car_Type_N          0
Car_Type_R          0
Car_Type_U          0
Accept              0
dtype: int64

In [34]:
features = ['Tier', 'FICO', 'Term', 'Amount', 'Previous_Rate', 'Competition_rate',
       'Rate', 'Cost_Funds', 'Partner Bin', 'Car_Type_N', 'Car_Type_R',
       'Car_Type_U']
label = ['Accept']
len(features), len(label)

(12, 1)

In [35]:
X_train = train[features]
y_train = train[label]
X_train.shape, y_train.shape

((109244, 12), (109244, 1))

## Process the test data  

In [36]:
test = pd.read_csv('test_LR.csv')
test.head()

Tier  FICO  Term   Amount  Previous_Rate  Competition_rate  Rate  \
0     2   725    72  30500.0              5              6.09  4.99   
1     1   739    60  25995.0            -10              4.79  4.79   
2     2   715    48  30000.0              5              5.19  4.79   
3     1   742    60  45000.0            -10              4.59  4.59   
4     4   649    60  27900.0            -10              4.49  6.99   

   Cost_Funds  Partner Bin  Car_Type_N  Car_Type_R  Car_Type_U  Accept  
0      1.1200            2           0           1           0       0  
1      1.9590            2           0           0           1       0  
2      1.1200            2           0           1           0       0  
3      1.5788            3           1           0           0       0  
4      1.3206            3           1           0           0       1

In [37]:
test.shape

(36415, 13)

In [38]:
test.columns

Index(['Tier', 'FICO', 'Term', 'Amount', 'Previous_Rate', 'Competition_rate',
       'Rate', 'Cost_Funds', 'Partner Bin', 'Car_Type_N', 'Car_Type_R',
       'Car_Type_U', 'Accept'],
      dtype='object')

In [39]:
test.isna().sum()

Tier                0
FICO                0
Term                0
Amount              0
Previous_Rate       0
Competition_rate    0
Rate                0
Cost_Funds          0
Partner Bin         0
Car_Type_N          0
Car_Type_R          0
Car_Type_U          0
Accept              0
dtype: int64

In [40]:
X_test = test[features]
y_test = test[label]
X_test.shape, y_test.shape

((36415, 12), (36415, 1))

## Logistic Regression  

In [56]:
logreg = LogisticRegression(max_iter=10000, random_state=17)
logreg

LogisticRegression(max_iter=10000, random_state=17)

In [57]:
# Fit the model on train data

logreg.fit(X_train, y_train)

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(max_iter=10000, random_state=17)

In [58]:
logreg.intercept_, logreg.coef_

(array([0.00789489]),
 array([[-1.34240017e-01, -2.05561083e-04,  3.18016153e-02,
         -9.44993094e-05,  2.78354937e-02,  3.53948212e-01,
         -2.27245651e-01,  2.90543987e-02, -3.77401804e-01,
         -7.80534526e-01, -5.22394983e-02,  8.40669547e-01]]))

In [59]:
# Predict on training data  
y_pred_train = logreg.predict(X_train)
y_pred_train.shape

(109244,)

In [60]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.85      0.94      0.89     85258
           1       0.64      0.39      0.49     23986

    accuracy                           0.82    109244
   macro avg       0.74      0.67      0.69    109244
weighted avg       0.80      0.82      0.80    109244



In [61]:
print(confusion_matrix(y_train, y_pred_train))

[[80036  5222]
 [14559  9427]]


In [62]:
# Predict on test data  
y_pred_test = logreg.predict(X_test)
y_pred_test.shape

(36415,)

In [63]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.84      0.94      0.89     28350
           1       0.64      0.39      0.49      8065

    accuracy                           0.82     36415
   macro avg       0.74      0.67      0.69     36415
weighted avg       0.80      0.82      0.80     36415



In [64]:
print(confusion_matrix(y_test, y_pred_test))

[[26545  1805]
 [ 4883  3182]]


`Q1`  

In [51]:
train.shape[0]

109244

`Q2`  

In [52]:
test.shape[0]

36415

`Q3`  

In [53]:
y_train.value_counts(normalize=True)

Accept
0         0.780436
1         0.219564
dtype: float64

`Q4`  

In [54]:
y_train.value_counts(normalize=True)

Accept
0         0.780436
1         0.219564
dtype: float64

`Q5`  

In [55]:
y_test.value_counts(normalize=True)

Accept
0         0.778525
1         0.221475
dtype: float64

`Q6`  

In [65]:
y_test.value_counts(normalize=True)

Accept
0         0.778525
1         0.221475
dtype: float64

`Q7`  

In [68]:
accuracy_score(y_train, y_pred_train)

0.8189282706601736

`Q8`  

In [71]:
precision_score(y_train, y_pred_train, pos_label=0) # Note: pos_label=0 for those who do not accept loans

0.8460912310375812

`Q9`  

In [74]:
recall_score(y_train, y_pred_train, pos_label=1)    # Note: pos_label=1 for those who accept loans

0.3930209288751772

`Q10`  

In [78]:
confusion_matrix(y_test, y_pred_test)

array([[26545,  1805],
       [ 4883,  3182]], dtype=int64)

`Q11`  

In [79]:
confusion_matrix(y_test, y_pred_test)

array([[26545,  1805],
       [ 4883,  3182]], dtype=int64)

`Q12`  

In [80]:
accuracy_score(y_test, y_pred_test)

0.8163394205684471

`Q13`  

In [82]:
precision_score(y_test, y_pred_test, pos_label=1)   # Note: pos_label=1 for those who accept loans

0.6380589532785241

`Q14`  

In [83]:
recall_score(y_test, y_pred_test, pos_label=1)   # Note: pos_label=1 for those who accept loans

0.3945443273403596

`Q15`  

In [86]:
print(precision_score(y_train, y_pred_train, pos_label=1))  # Note: pos_label=1 for those who accept loans
print(precision_score(y_test, y_pred_test, pos_label=1))    # Note: pos_label=1 for those who accept loans

0.6435251553007031
0.6380589532785241
